name : publish docker image
on: push

jobs:
  publish-docker-image-registry:
    name: Publish and push image to docker
    runs-on: ubuntu-latest
    steps:
    - name: checkout the repo
      uses: actions/checkout@v4.1.1
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERUSERNAME }}
        password: ${{ secrets.DOCKERPASSWORD }}
    
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v5.0.0
      with:
        images: herve2k/web-app-1
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }} ##these tags can include tags based git branches/commits etc..##
        labels: ${{ steps.meta.outputs.labels }}
